CREATE USER IF NOT EXISTS __DBUSER__@localhost IDENTIFIED BY '__DBPASS__';
CREATE DATABASE __DBNAME__;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,REFERENCES ON __DBNAME__.* TO __DBUSER__@localhost;
FLUSH PRIVILEGES;
